### ISSUE TITLE
部分代码缺失

### ISSUE THREAD

**Issue by WeiminLee** [niuzaisheng/ScreenAgent#1]
请补充部分缺失的代码，train/utils部分。这部分代码可以从cogagent-main工程中找到。谢谢

**Comment by niuzaisheng** [comment]
感谢提醒，会尽快补上。

**Comment by RiSyaoran** [comment]
> 感谢提醒，会尽快补上。

logger_util这部分也没能找到，能否也补充一下，感谢。
