### ISSUE TITLE
When the ScreenAgent model weights will be open source ?

### ISSUE THREAD

**Issue by butterluo** [niuzaisheng/ScreenAgent#10]
Greate Job and very appreciate it!
But When the ScreenAgent model weights will be open source ?

**Comment by niuzaisheng** [comment]
> Greate Job and very appreciate it! But When the ScreenAgent model weights will be open source ?

You can download form here: https://huggingface.co/niurl/ScreenAgent

**Comment by butterluo** [comment]
> > Greate Job and very appreciate it! But When the ScreenAgent model weights will be open source ?
> 
> You can download form here: https://huggingface.co/niurl/ScreenAgent

Thanks very much!
