### ISSUE TITLE
Headless Option

### ISSUE THREAD

**Issue by piperwolters** [niuzaisheng/ScreenAgent#27]
Thank you for releasing this work! 
Curious if you have a headless option or when you will support that?

**Comment by niuzaisheng** [comment]
Thank you for your interest, we have the plan, headless option can construct reinforcement learning training. But the problem right now is agent's performance , which has a hard time completing the full task without human intervention. So the collected sequences are almost all negative samples. We still need positive samples to improve model performance.
We are developing more convenient human-guided data collection pipeline, so the urgency of the headless option is not as strong. Alternatively you can refer to transforming [this project](https://github.com/niuzaisheng/ScreenAgentWebClient) in implementing your own headless mode, it's easier to write this in js than python.
