### ISSUE TITLE
在win用curl发送POST测试clipboard的正确格式

### ISSUE THREAD

**Issue by zhuhaier1992** [niuzaisheng/ScreenAgent#32]
在win中必须用双引号，因此dict中的双引号需加反斜杠：
`curl --location "http://localhost:8001/clipboard"  --header "Content-Type: application/json" --data "{\"text\":\"He
llo\", \"token\":\"secret\"}"`
或者：
`curl http://localhost:8001/clipboard -H "Content-Type: application/json" -d "{\"text\":\"Hello\", \"tok
en\":\"secret\"}"`

**Comment by niuzaisheng** [comment]
在开发时我们并没有对win进行针对性适配，所以可能会有一些问题，感谢您的反馈。
