### ISSUE TITLE
Action Type：up 和 down的含义

### ISSUE THREAD

**Issue by Lqf-HFNJU** [niuzaisheng/ScreenAgent#7]
您好！请问一下在ScreenAgent数据集里，除了文章中定义的action type之外，还存在“up”和“down”两种type，这两种type是什么意思呢？什么场景下会用到呢？
谢谢！

**Comment by niuzaisheng** [comment]
根据VNC协议的定义，鼠标的Click操作实际上是由Move->Down->Up（移动、按下、抬起）三个更细粒度的操作组成的；
鼠标的拖拽是由Move和Drag两个操作组成，而Drag操作由Down->Move->Up三个更细粒度的操作组成，因此我们保留了Up和Down这两种操作；
同理，键盘的按下操作也是由Down和Up先后执行完成的。
具体的实现方式可以参考`client/action.py`。

**Comment by Lqf-HFNJU** [comment]
谢谢！
